//Archivo solo de los equipos, Solo 3 Por ser mucha Cantidad
const equipos = [
    {
        id: 1,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Club_Atl%C3%A9tico_River_Plate_logo.svg/960px-Club_Atl%C3%A9tico_River_Plate_logo.svg.png",
        alt: "Escudo River",
        nombre: "River Plate",
        fundacionClub: "25 de mayo de 1901",
        descripcion: "El Club Atlético River Plate, fundado el 25 de mayo de 1901 en el barrio de La Boca tras la fusión de los clubes Santa Rosa y La Rosales, es una destacada entidad polideportiva argentina cuyo nombre rinde homenaje a la antigua denominación británica del Río de la Plata. Identificado por sus históricos colores blanco, rojo y negro, el equipo compite en la Primera División de Argentina y ejerce su localía en el estadio Mâs Monumental, el recinto con mayor capacidad del continente al albergar a 85.018 espectadores. Consolidado como uno de los clubes más exitosos del mundo, su palmarés totaliza 72 títulos, destacándose como el máximo ganador histórico de campeonatos de Primera División (38) y el más laureado del fútbol argentino desde la profesionalización en 1931, con 69 conquistas. Además, ostenta un gran dominio en las copas nacionales con 16 coronas, siendo el principal vencedor de la Supercopa Argentina y el Trofeo de Campeones, además de sumar tres títulos de la Copa Argentina.",
        pais: "Argentina",
        estadio: "https://i.pinimg.com/1200x/ff/a4/dd/ffa4ddca1d6708798058274ebdbe5bff.jpg",
        fundacionEstadio: 1938,
        nombreEstadio: "Estadio Mâs Monumental",
        capacidad: 85.018,
        ubicacion: "Nuñes, Capital Federal",
        jugadores: [
            { id: null, nombre: "Eduardo Coudet", posicion: "Entrenador", nacimiento: "12/09/1974", edad: 51, nacionalidad: "Argentina" },
            { id: 1, nombre: "Franco Armani", posicion: "Arquero", nacimiento: "16/10/1986", edad: 39, nacionalidad: "Argentina" },
            { id: 33, nombre: "Ezequiel Centurión", posicion: "Arquero", nacimiento: "20/05/1997", edad: 29, nacionalidad: "Argentina" },
            { id: 41, nombre: "Santiago Beltrán", posicion: "Arquero", nacimiento: "04/10/2004", edad: 21, nacionalidad: "Argentina" },
            { id: 2, nombre: "Tobías Ramirez", posicion: "Defensa Central", nacimiento: "11/11/2006", edad: 19, nacionalidad: "Argentina" },
            { id: 5, nombre: "Juan Carlos Portillo", posicion: "Defensa Central", nacimiento: "18/05/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 13, nombre: "Lautaro Rivero", posicion: "Defensa Central", nacimiento: "01/11/2003", edad: 22, nacionalidad: "Argentina" },
            { id: 16, nombre: "Fabricio Bustos", posicion: "Defensa Lateral Derecho", nacimiento: "28/04/1996", edad: 30, nacionalidad: "Argentina" },
            { id: 17, nombre: "Paulo Diaz", posicion: "Defensa Central", nacimiento: "25/08/1994", edad: 31, nacionalidad: "Chile" },
            { id: 18, nombre: "Matías Viña", posicion: "Defensa Lateral Izquierdo", nacimiento: "09/11/1997", edad: 28, nacionalidad: "Uruguay" },
            { id: 20, nombre: "German Pezzella", posicion: "Defensa Central", nacimiento: "27/06/1991", edad: 34, nacionalidad: "Argentina" },
            { id: 21, nombre: "Marcos Acuña", posicion: "Defensa Lateral Izquierdo", nacimiento: "28/10/1991", edad: 34, nacionalidad: "Argentina" },
            { id: 28, nombre: "Lucas Martínez Quarta", posicion: "Defensa Central", nacimiento: "10/05/1996", edad: 30, nacionalidad: "Argentina" },
            { id: 29, nombre: "Gonzalo Montiel", posicion: "Defensa Lateral Derecho", nacimiento: "01/01/1997", edad: 29, nacionalidad: "Argentina" },
            { id: 30, nombre: "Nicolás Otamendi", posicion: "Defensa Central", nacimiento: "12/02/1988", edad: 38, nacionalidad: "Argentina" },
            { id: 36, nombre: "Ulises Giménez", posicion: "Defensa Central", nacimiento: "01/01/2006", edad: 20, nacionalidad: "Argentina" },
            { id: null, nombre: "Elián Giménez", posicion: "Centrocampista defensivo", nacimiento: "23/03/2004", edad: 22, nacionalidad: "Argentina" },
            { id: 39, nombre: "Lucas Silva", posicion: "Centrocampista defensivo", nacimiento: "26/02/2007", edad: 19, nacionalidad: "Brasil" },
            { id: 6, nombre: "Anibal Moreno", posicion: "Centrocampista defensivo", nacimiento: "13/05/1999", edad: 27, nacionalidad: "Argentina" },
            { id: 10, nombre: "Juan Fernando Quintero", posicion: "Mediocampista Ofensivo", nacimiento: "18/01/1993", edad: 33, nacionalidad: "Colombia" },
            { id: 15, nombre: "Fausto Vera", posicion: "Centrocampista defensivo", nacimiento: "26/03/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 19, nombre: "Kendry Páez", posicion: "Mediocampista Ofensivo", nacimiento: "04/05/2007", edad: 19, nacionalidad: "Ecuador" },
            { id: 22, nombre: "Kevin Castaño", posicion: "Centrocampista defensivo", nacimiento: "29/09/2000", edad: 25, nacionalidad: "Colombia" },
            { id: 26, nombre: "Tomás Galván", posicion: "Mediocampista Ofensivo", nacimiento: "11/04/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 34, nombre: "Giuliano Galoppo", posicion: "Mediocampista Central", nacimiento: "18/06/1999", edad: 27, nacionalidad: "Argentina" },
            { id: 39, nombre: "Santiago Lencina", posicion: "Mediocampista Ofensivo", nacimiento: "04/09/2005", edad: 20, nacionalidad: "Argentina" },
            { id: 47, nombre: "Juan Cruz Meza", posicion: "Mediocampista Ofensivo", nacimiento: "14/03/2008", edad: 18, nacionalidad: "Argentina" },
            { id: null, nombre: "Leonel Jaime", posicion: "Delantero Izquierdo", nacimiento: "14/07/2006", edad: 19, nacionalidad: "Argentina" },
            { id: 7, nombre: "Maximiliano Salas", posicion: "Centro Delantero", nacimiento: "01/12/1997", edad: 28, nacionalidad: "Argentina" },
            { id: 8, nombre: "Maximiliano Meza", posicion: "Delantero Derecho", nacimiento: "15/12/1992", edad: 33, nacionalidad: "Argentina" },
            { id: 9, nombre: "Sebastián Driussi", posicion: "Centro Delantero", nacimiento: "09/02/1996", edad: 30, nacionalidad: "Argentina" },
            { id: 11, nombre: "Facundo Colidio", posicion: "Centro Delantero", nacimiento: "04/01/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 32, nombre: "Agustín Ruberto", posicion: "Centro Delantero", nacimiento: "14/01/2006", edad: 20, nacionalidad: "Argentina" },
            { id: 35, nombre: "Joaquín Freitas", posicion: "Centro Delantero", nacimiento: "02/12/2006", edad: 19, nacionalidad: "Argentina" },
            { id: 38, nombre: "Ian Subiabre", posicion: "Delantero Derecho", nacimiento: "01/01/2007", edad: 19, nacionalidad: "Argentina" }
        ]
    },

    {
        id: 2,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/CABJ70.png/960px-CABJ70.png",
        alt: "Escudo Boca",
        nombre: "Boca Juniors",
        fundacionClub: "3 de abril 1905",
        descripcion: "El Club Atlético Boca Juniors, fundado el 3 de abril de 1905 en el barrio porteño de La Boca por un grupo de adolescentes hijos de inmigrantes italianos, es una emblemática entidad deportiva argentina dedicada principalmente al fútbol masculino. El equipo disputa sus encuentros como local en el mítico estadio Alberto J. Armando, popularmente conocido como «La Bombonera», y compite en la Primera División desde 1913. Históricamente, ostenta el récord de ser el único club que ha participado en todas las temporadas desde el inicio del profesionalismo en 1931, acumulando la mayor cantidad de partidos jugados y la mayor permanencia ininterrumpida en la máxima categoría. A nivel nacional, se consolida como una de las instituciones más exitosas con 35 campeonatos de liga y un récord absoluto de 17 copas nacionales, destacándose como el máximo ganador de la Copa Argentina (cuatro títulos) y de la Copa de la Liga Profesional (dos títulos), sumado al reconocimiento honorífico de la Copa de Honor obtenida en 1925 tras su exitosa gira por Europa.",
        liga: "Liga Profesional de Futbol",
        pais: "Argentina",
        estadio: "https://i.pinimg.com/1200x/ff/6c/e4/ff6ce47fa3e3b7aa51c8517e5c95af90.jpg",
        fundacionEstadio: 1940,
        nombreEstadio: "Estadio Alberto José Armando",
        capacidad: 54.102,
        ubicacion: "La boca, Capital Federal",
        jugadores: [
            { id: null, nombre: "Rodolfo Arruabarrena", posicion: "Entrenador", nacimiento: "20/07/1975", edad: 50, nacionalidad: "Argentina" },
            { id: 1, nombre: "Agustín Marchesín", posicion: "Arquero", nacimiento: "16/03/1988", edad: 38, nacionalidad: "Argentina" },
            { id: 12, nombre: "Leandro Brey", posicion: "Arquero", nacimiento: "21/09/2002", edad: 23, nacionalidad: "Argentina" },
            { id: 13, nombre: "Javier García", posicion: "Arquero", nacimiento: "29/01/1987", edad: 39, nacionalidad: "Argentina" },
            { id: null, nombre: "Agustín Heredia", posicion: "Defensa Central", nacimiento: "16/06/1997", edad: 29, nacionalidad: "Argentina" },
            { id: 2, nombre: "Lautaro Di Lollo", posicion: "Defensa Central", nacimiento: "10/03/2004", edad: 22, nacionalidad: "Argentina" },
            { id: 3, nombre: "Lautaro Blanco", posicion: "Defensa Lateral Izquierdo", nacimiento: "19/02/1999", edad: 27, nacionalidad: "Argentina" },
            { id: 4, nombre: "Nicolás Figal", posicion: "Defensa Central", nacimiento: "03/04/1994", edad: 32, nacionalidad: "Argentina" },
            { id: 23, nombre: "Marcelo Weigandt", posicion: "Defensa Lateral Derecho", nacimiento: "11/01/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 24, nombre: "Juan Barinaga", posicion: "Defensa Lateral Derecho", nacimiento: "10/10/2000", edad: 25, nacionalidad: "Argentina" },
            { id: 26, nombre: "Marco Pellegrino", posicion: "Defensa Central", nacimiento: "18/07/2002", edad: 23, nacionalidad: "Argentina" },
            { id: 27, nombre: "Malcom Braida", posicion: "Defensa Lateral Izquierdo", nacimiento: "17/05/1997", edad: 29, nacionalidad: "Argentina" },
            { id: 32, nombre: "Ayrton Costa", posicion: "Defensa Central", nacimiento: "12/07/1999", edad: 26, nacionalidad: "Argentina" },
            { id: null, nombre: "Juan Ramirez", posicion: "Volante Izquierdo", nacimiento: "25/05/1993", edad: 33, nacionalidad: "Argentina" },
            { id: 5, nombre: "Leandro Paredes", posicion: "Centrocampista defensivo", nacimiento: "29/06/1994", edad: 31, nacionalidad: "Argentina" },
            { id: 6, nombre: "Rodrigo Battaglia", posicion: "Centrocampista defensivo", nacimiento: "12/07/1991", edad: 34, nacionalidad: "Argentina" },
            { id: 8, nombre: "Carlos Palacios", posicion: "Mediocampista Ofensivo", nacimiento: "20/07/2000", edad: 25, nacionalidad: "Chile" },
            { id: 15, nombre: "Williams Alarcón", posicion: "Mediocampista Central", nacimiento: "29/11/2000", edad: 25, nacionalidad: "Chile" },
            { id: 18, nombre: "Milton Delgado", posicion: "Centrocampista defensivo", nacimiento: "16/06/2005", edad: 21, nacionalidad: "Argentina" },
            { id: 19, nombre: "Agustín Martegani", posicion: "Mediocampista Ofensivo", nacimiento: "20/05/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 25, nombre: "Santiago Ascacibar", posicion: "Centrocampista defensivo", nacimiento: "25/02/1997", edad: 29, nacionalidad: "Argentina" },
            { id: 30, nombre: "Tomás Belmonte", posicion: "Centrocampista defensivo", nacimiento: "27/05/1998", edad: 28, nacionalidad: "Argentina" },
            { id: 36, nombre: "Tomás Aranda", posicion: "Mediocampista Ofensivo", nacimiento: "09/05/2007", edad: 19, nacionalidad: "Argentina" },
            { id: 38, nombre: "Camilo Rey Domenech", posicion: "Centrocampista defensivo", nacimiento: "10/03/2006", edad: 20, nacionalidad: "Argentina" },
            { id: null, nombre: "Nicolas Orsini", posicion: "Centro Delantero", nacimiento: "12/09/1994", edad: 31, nacionalidad: "Argentina" },
            { id: 7, nombre: "Exequiel Zeballos", posicion: "Delantero Derecho", nacimiento: "24/04/2002", edad: 24, nacionalidad: "Argentina" },
            { id: 9, nombre: "Milton Giménez", posicion: "Centro Delantero", nacimiento: "12/08/1996", edad: 29, nacionalidad: "Argentina" },
            { id: 10, nombre: "Édinson Cavani", posicion: "Centro Delantero", nacimiento: "14/02/1987", edad: 39, nacionalidad: "Uruguay" },
            { id: 11, nombre: "Lucas Janson", posicion: "Delantero Izquierdo", nacimiento: "16/08/1994", edad: 31, nacionalidad: "Argentina" },
            { id: 16, nombre: "Miguel Merentiel", posicion: "Centro Delantero", nacimiento: "24/02/1996", edad: 30, nacionalidad: "Uruguay" },
            { id: 20, nombre: "Alan Velasco", posicion: "Delantero Izquierdo", nacimiento: "27/07/2002", edad: 23, nacionalidad: "Argentina" },
            { id: 22, nombre: "Kevin Zenon", posicion: "Delantero Izquierdo", nacimiento: "30/07/2001", edad: 24, nacionalidad: "Argentina" },
            { id: 28, nombre: "Adam Bareiro", posicion: "Centro Delantero", nacimiento: "26/07/1996", edad: 29, nacionalidad: "Paraguay" },
            { id: 29, nombre: "Angel Romero", posicion: "Delantero Derecho", nacimiento: "04/07/1992", edad: 33, nacionalidad: "Paraguay" },
            { id: 37, nombre: "Gonzalo Gelini", posicion: "Delantero Derecho", nacimiento: "15/12/2006", edad: 19, nacionalidad: "Argentina" },
            { id: 41, nombre: "Iker Zufiaurre", posicion: "Delantero Derecho", nacimiento: "07/08/2005", edad: 20, nacionalidad: "Argentina" }
        ]
    },

    {
        id: 3,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Escudo_del_Club_Atl%C3%A9tico_V%C3%A9lez_Sarsfield.svg/960px-Escudo_del_Club_Atl%C3%A9tico_V%C3%A9lez_Sarsfield.svg.png",
        alt: "Escudo Velez",
        nombre: "Velez Sarsfield",
        fundacionClub: "1 de enero de 1910",
        descripcion: "El Club Atlético Vélez Sarsfield, conocido popularmente como «El Fortín», es una destacada asociación civil y entidad deportiva fundada el 1 de enero de 1910 en el barrio porteño de Liniers, cuya propiedad recae en sus más de 70.000 socios. Su principal disciplina es el fútbol masculino, compitiendo en la Liga Profesional Argentina y ejerciendo su localía en el estadio José Amalfitani. Consolidado como uno de los clubes más laureados del país, alcanzó su época de mayor éxito a partir de 1993 bajo la dirección técnica de Carlos Bianchi, sumando un total de 19 títulos oficiales en su historia: 11 campeonatos de Primera División, 3 copas nacionales y 5 coronas internacionales. Su mayor hito deportivo tuvo lugar en 1994 al conquistar la Copa Libertadores y consagrarse campeón del mundo tras vencer al A. C. Milan por 2-0 en la Copa Intercontinental en Tokio, logro que lo ubicó en un selecto grupo de 32 equipos a nivel global. A nivel local, su rival histórico es Ferro Carril Oeste, con quien conforma el tradicional clásico del oeste, un enfrentamiento que no se disputa desde el año 2000 por la ausencia de este último en la máxima categoría.",
        liga: "Liga Profesional de Futbol",
        pais: "Argentina",
        estadio: "https://i.pinimg.com/1200x/5f/4a/94/5f4a9477731883805d9e1bf1f0f9f1cd.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 1943,
        nombreEstadio: "Estadio José Amalfitani",
        capacidad: 49.543,
        ubicacion: "Liniers, Capital Federal",
        jugadores: [
            { id: null, nombre: "Guillermo Barros Schelotto", posicion: "Entrenador", nacimiento: "04/05/1973", edad: 53, nacionalidad: "Argentina" },
            { id: null, nombre: "Gustavo Barros Schelotto", posicion: "Asistente tecnico", nacimiento: "04/05/1973", edad: 53, nacionalidad: "Argentina" },
            { id: null, nombre: "Alvaro Busso", posicion: "Arquero", nacimiento: "11/10/2006", edad: 19, nacionalidad: "Argentina" },
            { id: 1, nombre: "Tomás Marchiori", posicion: "Arquero", nacimiento: "20/06/1995", edad: 31, nacionalidad: "Argentina" },
            { id: 12, nombre: "Álvaro Montero", posicion: "Arquero", nacimiento: "29/03/1995", edad: 31, nacionalidad: "Colombia" },
            { id: null, nombre: "Leo Cristaldo", posicion: "Defensa Central", nacimiento: "12/01/2009", edad: 17, nacionalidad: "Argentina" },
            { id: 2, nombre: "Emanuel Mammana", posicion: "Defensa Central", nacimiento: "10/02/1996", edad: 30, nacionalidad: "Argentina" },
            { id: 3, nombre: "Elias Gomez", posicion: "Defensa Lateral Izquierdo", nacimiento: "09/06/1994", edad: 32, nacionalidad: "Argentina" },
            { id: 4, nombre: "Joaquin García", posicion: "Defensa Lateral Derecho", nacimiento: "20/08/2001", edad: 24, nacionalidad: "Argentina" },
            { id: 6, nombre: "Aarón Quirós", posicion: "Defensa Central", nacimiento: "31/10/2001", edad: 24, nacionalidad: "Argentina" },
            { id: 16, nombre: "Lisandro Magallan", posicion: "Defensa Central", nacimiento: "27/09/1993", edad: 32, nacionalidad: "Argentina" },
            { id: 21, nombre: "Jano Gordon", posicion: "Defensa Lateral Derecho", nacimiento: "16/06/2004", edad: 22, nacionalidad: "Argentina" },
            { id: 32, nombre: "Thiago Silvero", posicion: "Defensa Central", nacimiento: "18/04/2006", edad: 20, nacionalidad: "Argentina" },
            { id: 49, nombre: "Demian Dominguez", posicion: "Defensa Lateral Izquierdo", nacimiento: "14/01/2006", edad: 20, nacionalidad: "Argentina" },
            { id: null, nombre: "Maximiliano Porcel", posicion: "Mediocampista Ofensivo", nacimiento: "02/01/2006", edad: 20, nacionalidad: "Argentina" },
            { id: 5, nombre: "Claudio Baeza", posicion: "Centrocampista defensivo", nacimiento: "23/12/1993", edad: 32, nacionalidad: "Chile" },
            { id: 8, nombre: "Lucas Robertone", posicion: "Mediocampista Central", nacimiento: "18/03/1997", edad: 29, nacionalidad: "Argentina" },
            { id: 10, nombre: "Diego Valdes", posicion: "Mediocampista Ofensivo", nacimiento: "30/01/1994", edad: 32, nacionalidad: "Chile" },
            { id: 22, nombre: "Manuel Lanzini", posicion: "Mediocampista Ofensivo", nacimiento: "15/02/1993", edad: 33, nacionalidad: "Argentina" },
            { id: 29, nombre: "Rodrigo Aliendro", posicion: "Mediocampista Central", nacimiento: "16/02/1991", edad: 35, nacionalidad: "Argentina" },
            { id: 50, nombre: "Tobias Andrada", posicion: "Mediocampista Central", nacimiento: "02/02/2007", edad: 19, nacionalidad: "Argentina" },
            { id: 7, nombre: "Imanol Machuca", posicion: "Delantero Derecho", nacimiento: "15/01/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 11, nombre: "Matias Pellegrini", posicion: "Delantero Izquierdo", nacimiento: "11/03/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 14, nombre: "Rodrigo Piñeiro", posicion: "Delantero Derecho", nacimiento: "05/05/1999", edad: 27, nacionalidad: "Uruguay" },
            { id: 15, nombre: "Dilan Godoy", posicion: "Centro Delantero", nacimiento: "05/02/2006", edad: 20, nacionalidad: "Argentina" },
            { id: 17, nombre: "Alex Veron", posicion: "Delantero Izquierdo", nacimiento: "24/10/2008", edad: 17, nacionalidad: "Argentina" },
            { id: 23, nombre: "Florián Monzón", posicion: "Centro Delantero", nacimiento: "03/01/2001", edad: 25, nacionalidad: "Argentina" },
            { id: 35, nombre: "Matias Arias", posicion: "Mediocampista Ofensivo", nacimiento: "08/05/2007", edad: 19, nacionalidad: "Argentina" }
        ]

    },

    {
        id: 4,
        escudo: "../img/escudos/FC_Barcelona.png",
        alt: "Escudo Barcelona",
        nombre: "FC Barcelona",
        fundacionClub: "20 de noviembre 1899",
        descripcion: "El Fútbol Club Barcelona, conocido popularmente como Barça y cuyos hinchas reciben el apelativo de «culés» o «blaugranas», es una emblemática entidad polideportiva fundada el 29 de noviembre de 1899 con sede en Barcelona, España. Destaca a nivel institucional por ser propiedad de sus más de 143.000 socios en lugar de una sociedad anónima deportiva, y por ostentar el honor de participar ininterrumpidamente en la Primera División de España desde su creación en 1929, certamen del cual fue su primer campeón histórico. Consolidado como uno de los gigantes del deporte, domina el palmarés nacional con 80 campeonatos y suma 22 trofeos internacionales, un desempeño que lo llevó a ser reconocido por la IFFHS como el mejor equipo mundial de las dos primeras décadas del siglo XXI. Además de sus hitos históricos —como ser el equipo con más presencias en los podios del Balón de Oro—, la institución brilla por su carácter polideportivo en disciplinas como el baloncesto, el balonmano o el fútbol sala, y destaca por ser el primer club europeo en coronarse campeón continental y lograr el triplete tanto con su primer equipo de fútbol masculino como con el femenino.",
        liga: "LaLiga",
        pais: "España",
        estadio: "https://i.pinimg.com/1200x/cf/cc/f4/cfccf424c6187f089088371ffb371a47.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 1957,
        nombreEstadio: "Estadio Spotify Camp Nou",
        capacidad: 99.534,
        ubicacion: "Liniers, Capital Federal",
        jugadores: [
            { id: null, nombre: "Hans-Dieter Flick", posicion: "Entrenador", nacimiento: "24/02/1965", edad: 61, nacionalidad: "Alemania" },
            { id: null, nombre: "Marcus Sorg", posicion: "Asistente tecnico", nacimiento: "24/12/1965", edad: 60, nacionalidad: "Alemania" },
            { id: null, nombre: "Toni Tapalovic", posicion: "Asistente tecnico", nacimiento: "10/10/1980", edad: 45, nacionalidad: "Alemania" },
            { id: 13, nombre: "Joan García", posicion: "Arquero", nacimiento: "04/05/2001", edad: 25, nacionalidad: "España" },
            { id: 25, nombre: "Wojciech Szczesny", posicion: "Arquero", nacimiento: "18/04/1990", edad: 36, nacionalidad: "Polonia" },
            { id: 2, nombre: "João Cancelo", posicion: "Defensa Lateral Derecho", nacimiento: "27/05/1994", edad: 32, nacionalidad: "Portugal" },
            { id: 3, nombre: "Alejandro Baldé", posicion: "Defensa Lateral Izquierdo", nacimiento: "18/10/2003", edad: 22, nacionalidad: "España" },
            { id: 4, nombre: "Ronald Araújo", posicion: "Defensa Central", nacimiento: "07/03/1999", edad: 27, nacionalidad: "Uruguay" },
            { id: 5, nombre: "Pau Cubarsí", posicion: "Defensa Central", nacimiento: "22/01/2007", edad: 19, nacionalidad: "España" },
            { id: 15, nombre: "Andreas Christensen", posicion: "Defensa Central", nacimiento: "10/04/1996", edad: 30, nacionalidad: "Dinamarca" },
            { id: 18, nombre: "Gerard Martín", posicion: "Defensa Central", nacimiento: "26/02/2002", edad: 24, nacionalidad: "España" },
            { id: 22, nombre: "Xavi Espart", posicion: "Defensa Lateral Derecho", nacimiento: "21/05/2007", edad: 19, nacionalidad: "España" },
            { id: 23, nombre: "Jules Koundé", posicion: "Defensa Lateral Derecho", nacimiento: "12/11/1998", edad: 27, nacionalidad: "Francia" },
            { id: 24, nombre: "Eric Garcia", posicion: "Defensa Central", nacimiento: "09/01/2001", edad: 25, nacionalidad: "España" },
            { id: 6, nombre: "Gavi", posicion: "Mediocampista Central", nacimiento: "05/08/2004", edad: 21, nacionalidad: "España" },
            { id: 8, nombre: "Pedri", posicion: "Mediocampista Central", nacimiento: "25/11/2002", edad: 23, nacionalidad: "España" },
            { id: 16, nombre: "Fermín López", posicion: "Mediocampista Ofensivo", nacimiento: "11/05/2003", edad: 23, nacionalidad: "España" },
            { id: 17, nombre: "Marc Casadó", posicion: "Centrocampista defensivo", nacimiento: "14/09/2003", edad: 22, nacionalidad: "España" },
            { id: 20, nombre: "Dani Olmo", posicion: "Mediocampista Ofensivo", nacimiento: "07/05/1998", edad: 28, nacionalidad: "España" },
            { id: 21, nombre: "Frenkie de Jong", posicion: "Mediocampista Central", nacimiento: "12/05/1997", edad: 29, nacionalidad: "Países Bajos" },
            { id: 22, nombre: "Marc Bernal", posicion: "Centrocampista defensivo", nacimiento: "26/05/2007", edad: 19, nacionalidad: "España" },
            { id: null, nombre: "Anthony Gordon", posicion: "Delantero Izquierdo", nacimiento: "24/02/2001", edad: 25, nacionalidad: "Inglaterra" },
            { id: 7, nombre: "Ferran Torres", posicion: "Centro Delantero", nacimiento: "29/02/2000", edad: 26, nacionalidad: "España" },
            { id: 9, nombre: "Robert Lewandowski", posicion: "Centro Delantero", nacimiento: "21/08/1988", edad: 37, nacionalidad: "Polonia" },
            { id: 10, nombre: "Lamine Yamal", posicion: "Delantero Derecho", nacimiento: "13/07/2007", edad: 18, nacionalidad: "España" },
            { id: 11, nombre: "Raphinha", posicion: "Delantero Izquierdo", nacimiento: "14/12/1996", edad: 29, nacionalidad: "Brasil" },
            { id: 14, nombre: "Marcus Rashford", posicion: "Delantero Izquierdo", nacimiento: "31/10/1997", edad: 28, nacionalidad: "Inglaterra" },
            { id: 19, nombre: "Roony Bardghji", posicion: "Delantero Derecho", nacimiento: "15/11/2005", edad: 20, nacionalidad: "Suecia" }
        ]
    },

    {
        id: 5,
        escudo: "../img/escudos/Real_Madrid_CF.png",
        alt: "Escudo Real",
        nombre: "Real Madrid",
        fundacionClub: "6 de marzo de 1902",
        descripcion: "El Real Madrid Club de Fútbol, identificado por su clásica indumentaria y apodado por sus aficionados como el equipo de los «blancos» o «merengues», es una histórica entidad polideportiva con sede en Madrid, España, registrada oficialmente el 6 de marzo de 1902. A nivel institucional, destaca por ser propiedad de sus más de 90.000 socios —evitando la figura de sociedad anónima deportiva— y por el honor de participar de forma ininterrumpida en la Primera División española desde su fundación en 1929, competición de la cual es el máximo ganador histórico, fue su primer líder y ostenta el récord de mayor puntuación en una sola edición. Aunque a lo largo de su historia desarrolló múltiples disciplinas que fueron desapareciendo, en la actualidad mantiene activa su prestigiosa sección de baloncesto y, desde el año 2019, amplió su estructura deportiva con la creación de su equipo de fútbol femenino tras la fusión por absorción del Club Deportivo TACON.",
        liga: "LaLiga",
        pais: "España",
        estadio: "https://i.pinimg.com/736x/0f/4b/26/0f4b268c71ff66a4c6f9887b580ef578.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 1947,
        nombreEstadio: "Estadio Santiago Bernabéu",
        capacidad: 81.044,
        ubicacion: "Madrid, España",
        jugadores: [
            { id: null, nombre: "José Mourinho", posicion: "Entrenador", nacimiento: "26/01/1963", edad: 63, nacionalidad: "Portugal" },
            { id: 1, nombre: "Thibaut Courtois", posicion: "Arquero", nacimiento: "11/05/1992", edad: 34, nacionalidad: "Bélgica" },
            { id: 13, nombre: "Andriy Lunin", posicion: "Arquero", nacimiento: "11/02/1999", edad: 27, nacionalidad: "Ucrania" },
            { id: null, nombre: "Marc Cucurella", posicion: "Defensa Lateral Izquierdo", nacimiento: "22/07/1998", edad: 27, nacionalidad: "España" },
            { id: null, nombre: "Ibrahima Konaté", posicion: "Defensa Central", nacimiento: "25/05/1999", edad: 27, nacionalidad: "Francia" },
            { id: 2, nombre: "Dani Carvajal", posicion: "Defensa Lateral Derecho", nacimiento: "11/01/1992", edad: 34, nacionalidad: "España" },
            { id: 3, nombre: "Éder Militão", posicion: "Defensa Central", nacimiento: "18/01/1998", edad: 28, nacionalidad: "Brasil" },
            { id: 4, nombre: "David Alaba", posicion: "Defensa Central", nacimiento: "24/06/1992", edad: 33, nacionalidad: "Austria" },
            { id: 12, nombre: "Trent Alexander-Arnold", posicion: "Defensa Lateral Derecho", nacimiento: "07/10/1998", edad: 27, nacionalidad: "Inglaterra" },
            { id: 17, nombre: "Raúl Asencio", posicion: "Defensa Central", nacimiento: "13/02/2003", edad: 23, nacionalidad: "España" },
            { id: 18, nombre: "Álvaro Carreras", posicion: "Defensa Lateral Izquierdo", nacimiento: "23/03/2003", edad: 23, nacionalidad: "España" },
            { id: 20, nombre: "Francisco Garcia", posicion: "Defensa Lateral Izquierdo", nacimiento: "14/08/1999", edad: 26, nacionalidad: "España" },
            { id: 22, nombre: "Antonio Rüdiger", posicion: "Defensa Central", nacimiento: "03/03/1993", edad: 33, nacionalidad: "Alemania" },
            { id: 23, nombre: "Ferland Mendy", posicion: "Defensa Lateral Izquierdo", nacimiento: "08/06/1995", edad: 31, nacionalidad: "Francia" },
            { id: 24, nombre: "Dean Huijsen", posicion: "Defensa Central", nacimiento: "14/04/2005", edad: 21, nacionalidad: "España" },
            { id: null, nombre: "Bernardo Silva", posicion: "Mediocampista Ofensivo", nacimiento: "10/08/1994", edad: 31, nacionalidad: "Portugal" },
            { id: 5, nombre: "Jude Bellingham", posicion: "Mediocampista Ofensivo", nacimiento: "29/06/2003", edad: 22, nacionalidad: "Inglaterra" },
            { id: 6, nombre: "Eduardo Camavinga", posicion: "Mediocampista Central", nacimiento: "10/11/2002", edad: 23, nacionalidad: "Francia" },
            { id: 8, nombre: "Federico Valverde", posicion: "Mediocampista Central", nacimiento: "22/07/1998", edad: 27, nacionalidad: "Uruguay" },
            { id: 8, nombre: "Manuel Ángel", posicion: "Mediocampista Central", nacimiento: "15/03/2004", edad: 22, nacionalidad: "España" },
            { id: 14, nombre: "Aurélien Tchouaméni", posicion: "Centrocampista defensivo", nacimiento: "27/01/2000", edad: 26, nacionalidad: "Francia" },
            { id: 15, nombre: "Arda Güler", posicion: "Mediocampista Ofensivo", nacimiento: "25/02/2005", edad: 21, nacionalidad: "Turquía" },
            { id: 19, nombre: "Dani Ceballos", posicion: "Mediocampista Central", nacimiento: "07/08/1996", edad: 29, nacionalidad: "España" },
            { id: 45, nombre: "Thiago Pitarch", posicion: "Mediocampista Central", nacimiento: "03/08/2007", edad: 18, nacionalidad: "España" },
            { id: 7, nombre: "Vinicius", posicion: "Delantero Izquierdo", nacimiento: "12/07/2000", edad: 25, nacionalidad: "Brasil" },
            { id: 10, nombre: "Kylian Mbappe", posicion: "Centro Delantero", nacimiento: "20/12/1998", edad: 27, nacionalidad: "Francia" },
            { id: 11, nombre: "Rodrygo", posicion: "Delantero Derecho", nacimiento: "09/01/2001", edad: 25, nacionalidad: "Brasil" },
            { id: 16, nombre: "Gonzalo García", posicion: "Centro Delantero", nacimiento: "24/03/2004", edad: 22, nacionalidad: "España" },
            { id: 21, nombre: "Brahim Diaz", posicion: "Delantero Derecho", nacimiento: "03/08/1999", edad: 26, nacionalidad: "Marruecos" },
            { id: 30, nombre: "Franco Mastantuono", posicion: "Delantero Derecho", nacimiento: "14/08/2007", edad: 18, nacionalidad: "Argentina" }
        ]
    },


    {
        id: 6,
        escudo: "../img/escudos/Atletico_Madrid_Logo_2024.png",
        alt: "Escudo Atletico",
        nombre: "Atlético de Madrid",
        fundacionClub: "26 de abril  de 1903",
        descripcion: "El Club Atlético de Madrid, S. A. D., fundado el 26 de abril de 1903 en la ciudad de Madrid, es una prestigiosa institución deportiva española que disputa sus encuentros como local en el estadio Metropolitano, con capacidad para 70.692 espectadores. Identificado por sus tradicionales colores rojo y blanco que le otorgan los apodos de «rojiblancos» o «colchoneros», el equipo es considerado uno de los tres clubes más grandes del fútbol español y ocupa el tercer puesto en la clasificación histórica de la Primera División, competición de la cual fue miembro fundador en 1929. A nivel nacional, ostenta un destacado palmarés que incluye once títulos de Liga, diez Copas del Rey y dos Supercopas de España. En el plano internacional, se erige como uno de los clubes europeos más laureados al conquistar tres Ligas Europa, una Recopa, tres Supercopas de Europa y la Copa Intercontinental de 1975 que lo acredita como campeón del mundo, además de haber disputado tres finales de la Liga de Campeones. Asimismo, la entidad destaca por su histórico papel pionero en el deporte femenino en España, contando en la actualidad con un exitoso equipo de fútbol que ha sumado a sus vitrinas múltiples Ligas, Copas de la Reina y una Supercopa.", 
        liga: "LaLiga",
        pais: "España",
        estadio: "https://i.pinimg.com/1200x/cb/1d/85/cb1d8531e8a5f4e20137c82542fea4f0.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 1994,
        nombreEstadio: "Estádio Cívitas Metropolitano",
        capacidad: 67.829,
        ubicacion: "Madrid, España",
        jugadores: [
            { id: null, nombre: "Diego Simeone", posicion: "Entrenador", nacimiento: "28/04/1970", edad: 56, nacionalidad: "Argentina" },
            { id: null, nombre: "Nelson Vivas", posicion: "Asistente tecnico", nacimiento: "18/10/1969", edad: 56, nacionalidad: "Argentina" },
            { id: 1, nombre: "Juan Musso", posicion: "Arquero", nacimiento: "06/05/1994", edad: 32, nacionalidad: "Argentina" },
            { id: 13, nombre: "Jan Oblak", posicion: "Arquero", nacimiento: "07/01/1993", edad: 33, nacionalidad: "Eslovenia" },
            { id: 2, nombre: "José María Giménez", posicion: "Defensa Central", nacimiento: "20/01/1995", edad: 31, nacionalidad: "Uruguay" },
            { id: 3, nombre: "Matteo Ruggeri", posicion: "Defensa Lateral Izquierdo", nacimiento: "11/07/2002", edad: 23, nacionalidad: "Italia" },
            { id: 14, nombre: "Marcos Llorente", posicion: "Defensa Lateral Derecho", nacimiento: "30/01/1995", edad: 31, nacionalidad: "España" },
            { id: 15, nombre: "Clément Lenglet", posicion: "Defensa Central", nacimiento: "17/06/1995", edad: 31, nacionalidad: "Francia" },
            { id: 16, nombre: "Nahuel Molina", posicion: "Defensa Lateral Derecho", nacimiento: "06/04/1998", edad: 28, nacionalidad: "Argentina" },
            { id: 17, nombre: "David Hancko", posicion: "Defensa Central", nacimiento: "13/12/1997", edad: 28, nacionalidad: "Eslovaquia" },
            { id: 18, nombre: "Marc Pubill", posicion: "Defensa Central", nacimiento: "20/06/2003", edad: 23, nacionalidad: "España" },
            { id: 24, nombre: "Robin Le Normand", posicion: "Defensa Central", nacimiento: "11/11/1996", edad: 29, nacionalidad: "España" },
            { id: 32, nombre: "Javier Bonar", posicion: "Defensa Lateral Derecho", nacimiento: "03/06/2005", edad: 21, nacionalidad: "España" },
            { id: 4, nombre: "Rodrigo Mendoza", posicion: "Mediocampista Central", nacimiento: "15/03/2005", edad: 21, nacionalidad: "España" },
            { id: 5, nombre: "Johnny Cardoso", posicion: "Mediocampista Central", nacimiento: "20/09/2001", edad: 24, nacionalidad: "Estados Unidos" },
            { id: 6, nombre: "Koke", posicion: "Mediocampista Central", nacimiento: "08/01/1992", edad: 34, nacionalidad: "España" },
            { id: 8, nombre: "Pablo Barrios", posicion: "Mediocampista Central", nacimiento: "15/06/2003", edad: 23, nacionalidad: "España" },
            { id: 21, nombre: "Obed Vargas", posicion: "Mediocampista Central", nacimiento: "05/08/2005", edad: 20, nacionalidad: "México" },
            { id: 47, nombre: "Javi Morcillo", posicion: "Mediocampista Central", nacimiento: "15/03/2006", edad: 20, nacionalidad: "España" },
            { id: 7, nombre: "Antoine Griezmann", posicion: "Segundo Delantero", nacimiento: "21/03/1991", edad: 35, nacionalidad: "Francia" },
            { id: 9, nombre: "Alexander Sorloth", posicion: "Centro Delantero", nacimiento: "05/12/1995", edad: 30, nacionalidad: "Noruega" },
            { id: 10, nombre: "Álex Baena", posicion: "Delantero Izquierdo", nacimiento: "20/07/2001", edad: 24, nacionalidad: "España" },
            { id: 11, nombre: "Thiago Almada", posicion: "Delantero Izquierdo", nacimiento: "26/04/2001", edad: 25, nacionalidad: "Argentina" },
            { id: 19, nombre: "Julián Álvarez", posicion: "Centro Delantero", nacimiento: "31/01/2000", edad: 26, nacionalidad: "Argentina" },
            { id: 20, nombre: "Giuliano Simeone", posicion: "Delantero Derecho", nacimiento: "18/12/2002", edad: 23, nacionalidad: "Argentina" },
            { id: 22, nombre: "Ademola Lookman", posicion: "Delantero Izquierdo", nacimiento: "20/10/1997", edad: 28, nacionalidad: "Nigeria" },
            { id: 23, nombre: "Nicolás González", posicion: "Delantero Izquierdo", nacimiento: "06/04/1998", edad: 28, nacionalidad: "Argentina" }
        ]
    },

    {
        id: 7,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg/960px-FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg.png",
        alt: "Escudo Bayer",
        nombre: "Bayern Munich",
        fundacionClub: "27 de febrero de 1900",
        descripcion: "El Bayern de Múnich, fundado el 27 de febrero de 1900 por un grupo de once jugadores liderados por Franz John, es una prestigiosa entidad polideportiva profesional con sede en Múnich, Alemania. Su principal disciplina es el fútbol, donde compite en la 1. Bundesliga y ejerce su localía desde el año 2005 en el Allianz Arena, un moderno recinto con capacidad para 75.024 espectadores. Institucionalmente, la gestión del equipo recae sobre la sociedad FC Bayern München AG, en la cual el club mantiene el 75 % de las acciones, compartiendo el resto con firmas como Adidas, Audi y Allianz. A nivel deportivo, domina de manera absoluta el fútbol nacional siendo el club más laureado del país con 35 títulos ligueros, 21 Copas y 11 Supercopas. En el escenario internacional se consagra como uno de los gigantes mundiales: elegido el tercer mejor Club del Siglo de la FIFA, ostenta el privilegio de conservar la Copa de Europa en propiedad tras su histórico tricampeonato (1974-1976), además de pertenecer al selecto grupo de equipos que ha conquistado las tres máximas competiciones continentales, logrado dos tripletes y alcanzado el histórico sextuplete.",
        liga: "Bundesliga",
        pais: "Alemania",
        estadio: "https://i.pinimg.com/736x/ac/b0/ce/acb0ced1e0743dbf71cf98460e150654.jpg",
        altEstadio: "Imagen estadio",
        fundacion: 2005,
        nombreEstadio: "Estadio Allianz Arena",
        capacidad: 75.024,
        ubicacion: "München, Alemania",
        jugadores: [
            { id: null, nombre: "Vincent Kompany", posicion: "Entrenador", nacimiento: "10/04/1986", edad: 40, nacionalidad: "Bélgica" },
            { id: null, nombre: "Aaron Danks", posicion: "Asistente tecnico", nacimiento: "15/06/1985", edad: 41, nacionalidad: "Inglaterra" },
            { id: 1, nombre: "Manuel Neuer", posicion: "Arquero", nacimiento: "27/03/1986", edad: 40, nacionalidad: "Alemania" },
            { id: 26, nombre: "Sven Ulreich", posicion: "Arquero", nacimiento: "03/08/1988", edad: 37, nacionalidad: "Alemania" },
            { id: 40, nombre: "Jonas Urbig", posicion: "Arquero", nacimiento: "08/08/2003", edad: 22, nacionalidad: "Alemania" },
            { id: 2, nombre: "Dayot Upamecano", posicion: "Defensa Central", nacimiento: "27/10/1998", edad: 27, nacionalidad: "Francia" },
            { id: 3, nombre: "Kim Min-Jae", posicion: "Defensa Central", nacimiento: "15/11/1996", edad: 29, nacionalidad: "Corea del Sur" },
            { id: 4, nombre: "Jonathan Tah", posicion: "Defensa Central", nacimiento: "11/02/1996", edad: 30, nacionalidad: "Alemania" },
            { id: 19, nombre: "Alphonso Davies", posicion: "Defensa Lateral Izquierdo", nacimiento: "02/11/2000", edad: 25, nacionalidad: "Canadá" },
            { id: 21, nombre: "Hiroki Ito", posicion: "Defensa Central", nacimiento: "12/05/1999", edad: 27, nacionalidad: "Japón" },
            { id: 27, nombre: "Konrad Laimer", posicion: "Defensa Lateral Derecho", nacimiento: "27/05/1997", edad: 29, nacionalidad: "Austria" },
            { id: 44, nombre: "Josip Stanišić", posicion: "Defensa Lateral Derecho", nacimiento: "02/04/2000", edad: 26, nacionalidad: "Croacia" },
            { id: 6, nombre: "Joshua Kimmich", posicion: "Centrocampista defensivo", nacimiento: "08/02/1995", edad: 31, nacionalidad: "Alemania" },
            { id: 8, nombre: "Leon Goretzka", posicion: "Mediocampista Central", nacimiento: "06/02/1995", edad: 31, nacionalidad: "Alemania" },
            { id: 10, nombre: "Jamal Musiala", posicion: "Mediocampista Ofensivo", nacimiento: "26/02/2003", edad: 23, nacionalidad: "Alemania" },
            { id: 20, nombre: "Tom Bischof", posicion: "Mediocampista Central", nacimiento: "28/06/2005", edad: 20, nacionalidad: "Alemania" },
            { id: 39, nombre: "Bara Sapoko Ndiaye", posicion: "Mediocampista Central", nacimiento: "31/12/2007", edad: 18, nacionalidad: "Senegal" },
            { id: 42, nombre: "Lennart Karl", posicion: "Mediocampista Ofensivo", nacimiento: "22/02/2008", edad: 18, nacionalidad: "Alemania" },
            { id: 45, nombre: "Aleksandar Pavlović", posicion: "Centrocampista defensivo", nacimiento: "03/05/2004", edad: 22, nacionalidad: "Alemania" },
            { id: 7, nombre: "Serge Gnabry", posicion: "Delantero Izquierdo", nacimiento: "14/07/1995", edad: 30, nacionalidad: "Alemania" },
            { id: 9, nombre: "Harry Kane", posicion: "Centro Delantero", nacimiento: "28/07/1993", edad: 32, nacionalidad: "Inglaterra" },
            { id: 11, nombre: "Nicolas Jackson", posicion: "Centro Delantero", nacimiento: "20/06/2001", edad: 25, nacionalidad: "Senegal" },
            { id: 14, nombre: "Luis Díaz", posicion: "Delantero Izquierdo", nacimiento: "13/01/1997", edad: 29, nacionalidad: "Colombia" },
            { id: 17, nombre: "Michael Olise", posicion: "Delantero Derecho", nacimiento: "12/12/2001", edad: 24, nacionalidad: "Francia" }
        ]
    },



    {
        id: 8,
        escudo: "../img/escudos/manchester-utd.png",
        alt: "Escudo United",
        nombre: "Manchester United",
        fundacionClub: "16 de abril de 1878",
        descripcion: "El Manchester United Football Club, fundado el 16 de abril de 1878 bajo el nombre de Newton Heath LYR y rebautizado con su denominación actual en 1902, es una histórica y popular institución deportiva inglesa que compite en la Premier League y ejerce su localía desde 1910 en el mítico estadio Old Trafford. A lo largo de su historia, el club supo sobreponerse a duras tragedias como el desastre aéreo de Múnich en 1958 para alcanzar la gloria deportiva y vivir una época dorada bajo el mando de Sir Alex Ferguson, logrando en 1999 un histórico «triplete» inédito en el balompié inglés. A nivel nacional, ostenta el récord de 20 títulos de liga, acompañados por 13 FA Cups, 6 Copas de la Liga y 21 Supercopas; mientras que en el plano continental suma 3 Ligas de Campeones, una Liga Europa, una Recopa y una Supercopa de Europa. Además, se erige como el primer y máximo ganador británico de títulos mundiales tras conquistar la Copa Intercontinental en 1999 y el Mundial de Clubes en 2008, consolidándose no solo como una potencia deportiva, sino también como una de las franquicias más valiosas financieramente y con mayor cantidad de seguidores en todo el mundo.",
        liga: "Premier League",
        pais: "Inglaterra",
        estadio: "https://i.pinimg.com/1200x/09/46/7a/09467ae4ff3595f7d8f8993ba4aaa6be.jpg",
        altEstadio: "Imagen estadio",
        fundacion: 1910,
        nombreEstadio: "Estadio Old Trafford",
        capacidad: 74.310,
        ubicacion: "Manchester, Inglaterra",
        jugadores: [
            { id: null, nombre: "Michael Carrick", posicion: "Entrenador", nacimiento: "28/07/1981", edad: 44, nacionalidad: "Inglaterra" },
            { id: 1, nombre: "Altay Bayindir", posicion: "Arquero", nacimiento: "14/04/1998", edad: 28, nacionalidad: "Turquía" },
            { id: 22, nombre: "Tom Heaton", posicion: "Arquero", nacimiento: "15/04/1986", edad: 40, nacionalidad: "Inglaterra" },
            { id: 31, nombre: "Senne Lammens", posicion: "Arquero", nacimiento: "07/07/2002", edad: 23, nacionalidad: "Bélgica" },
            { id: 2, nombre: "Diogo Dalot", posicion: "Defensa Lateral Derecho", nacimiento: "18/03/1999", edad: 27, nacionalidad: "Portugal" },
            { id: 3, nombre: "Noussair Mazraoui", posicion: "Defensa Lateral Derecho", nacimiento: "14/11/1997", edad: 28, nacionalidad: "Marruecos" },
            { id: 4, nombre: "Matthijs de Ligt", posicion: "Defensa Central", nacimiento: "12/08/1999", edad: 26, nacionalidad: "Países Bajos" },
            { id: 5, nombre: "Harry Maguire", posicion: "Defensa Central", nacimiento: "05/03/1993", edad: 33, nacionalidad: "Inglaterra" },
            { id: 6, nombre: "Lisandro Martínez", posicion: "Defensa Central", nacimiento: "18/01/1998", edad: 28, nacionalidad: "Argentina" },
            { id: 12, nombre: "Tyrell Malacia", posicion: "Defensa Lateral Izquierdo", nacimiento: "17/08/1999", edad: 26, nacionalidad: "Países Bajos" },
            { id: 13, nombre: "Patrick Dorgu", posicion: "Delantero Izquierdo", nacimiento: "26/10/2004", edad: 21, nacionalidad: "Dinamarca" },
            { id: 15, nombre: "Leny Yoro", posicion: "Defensa Central", nacimiento: "13/11/2005", edad: 20, nacionalidad: "Francia" },
            { id: 23, nombre: "Luke Shaw", posicion: "Defensa Lateral Izquierdo", nacimiento: "12/07/1995", edad: 30, nacionalidad: "Inglaterra" },
            { id: 26, nombre: "Ayden Heaven", posicion: "Defensa Central", nacimiento: "22/09/2006", edad: 19, nacionalidad: "Inglaterra" },
            { id: 7, nombre: "Mason Mount", posicion: "Mediocampista Ofensivo", nacimiento: "10/01/1999", edad: 27, nacionalidad: "Inglaterra" },
            { id: 8, nombre: "Bruno Fernandes", posicion: "Mediocampista Ofensivo", nacimiento: "08/09/1994", edad: 31, nacionalidad: "Portugal" },
            { id: 18, nombre: "Casemiro", posicion: "Centrocampista defensivo", nacimiento: "23/02/1992", edad: 34, nacionalidad: "Brasil" },
            { id: 25, nombre: "Manuel Ugarte", posicion: "Centrocampista defensivo", nacimiento: "11/04/2001", edad: 25, nacionalidad: "Uruguay" },
            { id: 37, nombre: "Kobbie Mainoo", posicion: "Centrocampista defensivo", nacimiento: "19/04/2005", edad: 21, nacionalidad: "Inglaterra" },
            { id: 10, nombre: "Matheus Cunha", posicion: "Segundo Delantero", nacimiento: "27/05/1999", edad: 27, nacionalidad: "Brasil" },
            { id: 11, nombre: "Joshua Zirkzee", posicion: "Centro Delantero", nacimiento: "22/05/2001", edad: 25, nacionalidad: "Países Bajos" },
            { id: 16, nombre: "Amad Diallo", posicion: "Delantero Derecho", nacimiento: "11/07/2002", edad: 23, nacionalidad: "Costa de Marfil" },
            { id: 19, nombre: "Bryan Mbeumo", posicion: "Delantero Derecho", nacimiento: "07/08/1999", edad: 26, nacionalidad: "Camerún" },
            { id: 30, nombre: "Benjamin Šeško", posicion: "Centro Delantero", nacimiento: "31/05/2003", edad: 23, nacionalidad: "Eslovenia" }
        ]
    },



    {
        id: 9,
        escudo: "../img/escudos/Manchester-City.png",
        alt: "Escudo City",
        nombre: "Manchester City",
        fundacionClub: "23 de noviembre de 1880",
        descripcion: "El Manchester City Football Club, fundado originariamente el 23 de noviembre de 1880 como St. Mark's (West Gorton) y rebautizado con su actual denominación en 1894, es un poderoso equipo inglés que compite en la Premier League y ejerce su localía en el Etihad Stadium desde 2003. Identificado históricamente por su característica camiseta celeste, el club atravesó una exitosa etapa a fines de los años 60 y principios de los 70, seguida de una profunda decadencia que lo llevó a descender hasta la tercera división en 1998. Sin embargo, tras recuperar su lugar en la máxima categoría y ser adquirido en 2008 por el grupo inversor Abu Dhabi United Group, la institución vivió un renacer sin precedentes que lo ha posicionado como uno de los clubes más ricos y valiosos del mundo. En su palmarés total acumula diez títulos de liga, siete FA Cups, ocho Copas de la Liga y siete Community Shields, destacándose en 2019 al convertirse en el primer equipo masculino inglés en conseguir el triplete doméstico. A nivel internacional, alcanzó la gloria máxima en 2023 al conquistar su primera Liga de Campeones frente al Inter de Milán y el Mundial de Clubes goleando al Fluminense, los cuales se suman a una histórica Recopa de Europa y una Supercopa de Europa, coronando un proyecto global que hoy se expande con la propiedad de múltiples equipos alrededor del mundo y que mantiene una encarnizada e histórica rivalidad vecinal con el Manchester United.",
        liga: "Premier League",
        pais: "Inglaterra",
        estadio: "https://i.pinimg.com/1200x/fb/28/8f/fb288fc8fc3a69d4ffb826746e41b94a.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 2002,
        nombreEstadio: "Estadio Etihad Stadium",
        capacidad: 53.400,
        ubicacion: "Manchester, Inglaterra",
        jugadores: [
            { id: null, nombre: "Pep Guardiola", posicion: "Entrenador", nacimiento: "18/01/1971", edad: 55, nacionalidad: "España" },
            { id: null, nombre: "Pepijn Lijnders", posicion: "Asistente tecnico", nacimiento: "24/01/1983", edad: 43, nacionalidad: "Países Bajos" },
            { id: 1, nombre: "James Trafford", posicion: "Arquero", nacimiento: "10/10/2002", edad: 23, nacionalidad: "Inglaterra" },
            { id: 13, nombre: "Marcus Bettinelli", posicion: "Arquero", nacimiento: "24/05/1992", edad: 34, nacionalidad: "Inglaterra" },
            { id: 25, nombre: "Gianluigi Donnarumma", posicion: "Arquero", nacimiento: "25/02/1999", edad: 27, nacionalidad: "Italia" },
            { id: 3, nombre: "Ruben Dias", posicion: "Defensa Central", nacimiento: "14/05/1997", edad: 29, nacionalidad: "Portugal" },
            { id: 5, nombre: "John Stones", posicion: "Defensa Central", nacimiento: "28/05/1994", edad: 32, nacionalidad: "Inglaterra" },
            { id: 6, nombre: "Nathan Aké", posicion: "Defensa Central", nacimiento: "18/02/1995", edad: 31, nacionalidad: "Países Bajos" },
            { id: 15, nombre: "Marc Guéhi", posicion: "Defensa Central", nacimiento: "13/07/2000", edad: 25, nacionalidad: "Inglaterra" },
            { id: 21, nombre: "Rayan Ait Nouri", posicion: "Defensa Lateral Izquierdo", nacimiento: "06/06/2001", edad: 25, nacionalidad: "Argelia" },
            { id: 24, nombre: "Josko Gvardiol", posicion: "Defensa Central", nacimiento: "23/01/2002", edad: 24, nacionalidad: "Croacia" },
            { id: 27, nombre: "Matheus Nunes", posicion: "Defensa Lateral Derecho", nacimiento: "27/08/1998", edad: 27, nacionalidad: "Portugal" },
            { id: 33, nombre: "Nico O'Reilly", posicion: "Defensa Lateral Izquierdo", nacimiento: "21/03/2005", edad: 21, nacionalidad: "Inglaterra" },
            { id: 45, nombre: "Abdukodir Khusanov", posicion: "Defensa Central", nacimiento: "29/02/2004", edad: 22, nacionalidad: "Uzbekistán" },
            { id: 68, nombre: "Max Alleyne", posicion: "Defensa Central", nacimiento: "21/07/2005", edad: 20, nacionalidad: "Inglaterra" },
            { id: 82, nombre: "Rico Lewis", posicion: "Defensa Lateral Derecho", nacimiento: "21/11/2004", edad: 21, nacionalidad: "Inglaterra" },
            { id: 4, nombre: "Tijjani Reijnders", posicion: "Mediocampista Central", nacimiento: "29/07/1998", edad: 27, nacionalidad: "Países Bajos" },
            { id: 8, nombre: "Mateo Kovacic", posicion: "Mediocampista Central", nacimiento: "06/05/1994", edad: 32, nacionalidad: "Croacia" },
            { id: 10, nombre: "Rayan Cherki", posicion: "Mediocampista Ofensivo", nacimiento: "17/08/2003", edad: 22, nacionalidad: "Francia" },
            { id: 14, nombre: "Nico González", posicion: "Centrocampista defensivo", nacimiento: "03/01/2002", edad: 24, nacionalidad: "España" },
            { id: 16, nombre: "Rodri Hernández", posicion: "Centrocampista defensivo", nacimiento: "22/06/1996", edad: 29, nacionalidad: "España" },
            { id: 41, nombre: "Sverre Nypan", posicion: "Mediocampista Central", nacimiento: "19/12/2006", edad: 19, nacionalidad: "Noruega" },
            { id: 44, nombre: "Kalvin Phillips", posicion: "Centrocampista defensivo", nacimiento: "02/12/1995", edad: 30, nacionalidad: "Inglaterra" },
            { id: 47, nombre: "Phil Foden", posicion: "Mediocampista Ofensivo", nacimiento: "28/05/2000", edad: 26, nacionalidad: "Inglaterra" },
            { id: 7, nombre: "Omar Marmoush", posicion: "Centro Delantero", nacimiento: "07/02/1999", edad: 27, nacionalidad: "Egipto" },
            { id: 9, nombre: "Erling Haaland", posicion: "Centro Delantero", nacimiento: "21/07/2000", edad: 25, nacionalidad: "Noruega" },
            { id: 11, nombre: "Jeremy Doku", posicion: "Delantero Izquierdo", nacimiento: "27/05/2002", edad: 24, nacionalidad: "Bélgica" },
            { id: 26, nombre: "Savinho", posicion: "Delantero Izquierdo", nacimiento: "10/04/2004", edad: 22, nacionalidad: "Brasil" },
            { id: 42, nombre: "Antoine Semenyo", posicion: "Delantero Derecho", nacimiento: "07/01/2000", edad: 26, nacionalidad: "Ghana" }
        ]
    },

    {
        id: 10,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Escudo_del_Par%C3%ADs_Saint-Germain_temporada_2025-26.png",
        alt: "Escudo Psg",
        nombre: "Paris Saint-Germain",
        fundacionClub: "12 de agosto de 1970",
        descripcion: "El Paris Saint-Germain Football Club (PSG) es una destacada entidad polideportiva con sede en París, fundada el 12 de agosto de 1970 tras la fusión del Paris Football Club y el Stade Saint-Germain, que hace las veces de local en su emblemático estadio Parc des Princes desde 1973 y cuenta con el Camp des Loges como centro de formación. Compitiendo en la Ligue 1, se ha consolidado como el club más laureado de Francia con 54 títulos oficiales a nivel nacional, entre los que destacan trece Ligas y dieciséis Copas. En el ámbito internacional, es el equipo francés más exitoso con seis conquistas, incluyendo la Recopa de Europa (1996), la Copa Intertoto (2001), dos Ligas de Campeones de la UEFA (2024-25 y 2025-26), la Supercopa de Europa (2025) y la Copa Intercontinental de la FIFA (2025), sumado a notables subcampeonatos como el de la Champions en 2019-20 y el Mundial de Clubes en 2025. Todo este dominio deportivo lo ha llevado a liderar la clasificación por equipos de la UEFA en 1998 y a ser reconocido como el mejor equipo del año por la IFFHS en dos ocasiones (1994 y 2025).",
        liga: "Ligue 1",
        pais: "Francia",
        estadio: "https://i.pinimg.com/1200x/23/0d/18/230d18c2458a3769eb90c5e5f2f8f683.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 1973,
        nombreEstadio: "Estadio Parc Des Princes",
        capacidad: 48.583,
        ubicacion: "Paris, Francia",
        jugadores: [
            { id: null, nombre: "Luis Enrique", posicion: "Entrenador", nacimiento: "08/05/1970", edad: 56, nacionalidad: "España" },
            { id: null, nombre: "Rafel Pol", posicion: "Asistente tecnico", nacimiento: "13/01/1987", edad: 39, nacionalidad: "España" },
            { id: 30, nombre: "Lucas Chevalier", posicion: "Arquero", nacimiento: "06/11/2001", edad: 24, nacionalidad: "Francia" },
            { id: 39, nombre: "Matvey Safonov", posicion: "Arquero", nacimiento: "25/02/1999", edad: 27, nacionalidad: "Rusia" },
            { id: 89, nombre: "Renato Marin", posicion: "Arquero", nacimiento: "10/07/2006", edad: 19, nacionalidad: "Brasil" },
            { id: 2, nombre: "Hakimi", posicion: "Defensa Lateral Derecho", nacimiento: "04/11/1998", edad: 27, nacionalidad: "Marruecos" },
            { id: 4, nombre: "Beraldo", posicion: "Defensa Central", nacimiento: "24/11/2003", edad: 22, nacionalidad: "Brasil" },
            { id: 5, nombre: "Marquinhos", posicion: "Defensa Central", nacimiento: "14/05/1994", edad: 32, nacionalidad: "Brasil" },
            { id: 6, nombre: "Ilya Zabarnyi", posicion: "Defensa Central", nacimiento: "01/09/2002", edad: 23, nacionalidad: "Ucrania" },
            { id: 21, nombre: "Lucas Hernández", posicion: "Defensa Lateral Izquierdo", nacimiento: "14/02/1996", edad: 30, nacionalidad: "Francia" },
            { id: 25, nombre: "Nuno Mendes", posicion: "Defensa Lateral Izquierdo", nacimiento: "19/06/2002", edad: 24, nacionalidad: "Portugal" },
            { id: 51, nombre: "Willian Pacho", posicion: "Defensa Central", nacimiento: "16/10/2001", edad: 24, nacionalidad: "Ecuador" },
            { id: 8, nombre: "Fabián Ruiz", posicion: "Mediocampista Central", nacimiento: "03/04/1996", edad: 30, nacionalidad: "España" },
            { id: 17, nombre: "Vitinha", posicion: "Centrocampista defensivo", nacimiento: "13/02/2000", edad: 26, nacionalidad: "Portugal" },
            { id: 19, nombre: "Lee Kang-in", posicion: "Mediocampista Ofensivo", nacimiento: "19/02/2001", edad: 25, nacionalidad: "Corea del Sur" },
            { id: 24, nombre: "Senny Mayulu", posicion: "Mediocampista Central", nacimiento: "17/05/2006", edad: 20, nacionalidad: "Francia" },
            { id: 27, nombre: "Dro Fernández", posicion: "Mediocampista Ofensivo", nacimiento: "12/01/2008", edad: 18, nacionalidad: "España" },
            { id: 33, nombre: "Warren Zaire-Emery", posicion: "Mediocampista Central", nacimiento: "08/03/2006", edad: 20, nacionalidad: "Francia" },
            { id: 87, nombre: "João Neves", posicion: "Mediocampista Central", nacimiento: "27/09/2004", edad: 21, nacionalidad: "Portugal" },
            { id: 7, nombre: "Khvicha Kvaratskhelia", posicion: "Delantero Izquierdo", nacimiento: "12/02/2001", edad: 25, nacionalidad: "Georgia" },
            { id: 9, nombre: "Gonçalo Ramos", posicion: "Centro Delantero", nacimiento: "20/06/2001", edad: 25, nacionalidad: "Portugal" },
            { id: 10, nombre: "Ousmane Dembélé", posicion: "Centro Delantero", nacimiento: "15/05/1997", edad: 29, nacionalidad: "Francia" },
            { id: 14, nombre: "Désiré Doué", posicion: "Delantero Derecho", nacimiento: "03/06/2005", edad: 21, nacionalidad: "Francia" },
            { id: 29, nombre: "Bradley Barcola", posicion: "Delantero Izquierdo", nacimiento: "02/09/2002", edad: 23, nacionalidad: "Francia" },
            { id: 47, nombre: "Quentin Ndjantou", posicion: "Delantero Izquierdo", nacimiento: "23/07/2007", edad: 18, nacionalidad: "Francia" },
            { id: 49, nombre: "Ibrahim Mbaye", posicion: "Delantero Derecho", nacimiento: "24/01/2008", edad: 18, nacionalidad: "Francia" }
        ]
    },



    {
        id: 11,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/960px-FC_Internazionale_Milano_2021.svg.png",
        alt: "Escudo Inter",
        nombre: "Inter de Milán",
        fundacionClub: "9 marzo de 1908",
        descripcion: "El Football Club Internazionale Milano, fundado el 9 de marzo de 1908 y comúnmente conocido como Inter de Milán, es un prestigioso club de fútbol de la región de Lombardía, Italia. Identificado por sus tradicionales colores negro y azul que le otorgan el apodo de conjunto «nerazzurro», ejerce su localía en el mítico estadio Giuseppe Meazza (San Siro), el recinto más grande del país que comparte con su clásico rival, el A. C. Milan, con quien disputa el famoso «Derby della Madonnina». A nivel nacional, ostenta el enorme orgullo de ser el único club que ha participado ininterrumpidamente en todas las ediciones de la Serie A desde su instauración en 1929, acumulando 39 títulos domésticos que lo consolidan como el segundo equipo más exitoso de Italia. En el ámbito internacional, su glorioso palmarés abarca tres Ligas de Campeones de la UEFA, tres Copas de la UEFA y tres campeonatos mundiales (dos Copas Intercontinentales y un Mundial de Clubes), destacándose por ser el primer y único equipo italiano en alcanzar el histórico triplete —y posterior quintuplete— en el año 2010. Respaldado por una enorme base de aficionados a nivel mundial y una gran valoración económica, el Inter ha sido reconocido en múltiples ocasiones por la IFFHS como uno de los mejores equipos del mundo y de Europa a lo largo de los siglos XX y XXI.",
        liga: "Serie A",
        pais: "Italia",
        estadio: "https://i.pinimg.com/736x/5b/38/8a/5b388ae87332e066f427c4df70316ce9.jpg",
        altEstadio: "Imagen estadio",
        fundacionEstadio: 1926,
        nombreEstadio: "Estadio San Sario",
        capacidad: 80.018,
        ubicacion: "Milano, Italia",
        jugadores: [
            { id: null, nombre: "Cristian Chivu", posicion: "Entrenador", nacimiento: "26/10/1980", edad: 45, nacionalidad: "Rumania" },
            { id: null, nombre: "Aleksandar Kolarov", posicion: "Asistente tecnico", nacimiento: "10/11/1985", edad: 40, nacionalidad: "Serbia" },
            { id: 1, nombre: "Yann Sommer", posicion: "Arquero", nacimiento: "17/12/1988", edad: 37, nacionalidad: "Suiza" },
            { id: 12, nombre: "Raffaele Di Gennaro", posicion: "Arquero", nacimiento: "03/10/1993", edad: 32, nacionalidad: "Italia" },
            { id: 13, nombre: "Josep Martinez", posicion: "Arquero", nacimiento: "27/05/1998", edad: 28, nacionalidad: "España" },
            { id: 2, nombre: "Denzel Dumfries", posicion: "Defensa Lateral Derecho", nacimiento: "18/04/1996", edad: 30, nacionalidad: "Países Bajos" },
            { id: 6, nombre: "Stefan de Vrij", posicion: "Defensa Central", nacimiento: "05/02/1992", edad: 34, nacionalidad: "Países Bajos" },
            { id: 25, nombre: "Manuel Akanji", posicion: "Defensa Central", nacimiento: "19/07/1995", edad: 30, nacionalidad: "Suiza" },
            { id: 30, nombre: "Carlos Augusto", posicion: "Defensa Lateral Izquierdo", nacimiento: "07/01/1999", edad: 27, nacionalidad: "Brasil" },
            { id: 31, nombre: "Yann Bisseck", posicion: "Defensa Central", nacimiento: "29/11/2000", edad: 25, nacionalidad: "Alemania" },
            { id: 32, nombre: "Federico Dimarco", posicion: "Defensa Lateral Izquierdo", nacimiento: "10/11/1997", edad: 28, nacionalidad: "Italia" },
            { id: 95, nombre: "Alessandro Bastoni", posicion: "Defensa Central", nacimiento: "13/04/1999", edad: 27, nacionalidad: "Italia" },
            { id: null, nombre: "Aleksandar Stankovic", posicion: "Mediocampista Central", nacimiento: "03/08/2005", edad: 20, nacionalidad: "Serbia" },
            { id: 7, nombre: "Piotr Zielinski", posicion: "Mediocampista Central", nacimiento: "20/05/1994", edad: 32, nacionalidad: "Polonia" },
            { id: 8, nombre: "Petar Sucic", posicion: "Mediocampista Central", nacimiento: "25/10/2003", edad: 22, nacionalidad: "Croacia" },
            { id: 11, nombre: "Luis Henrique", posicion: "Volante Derecho", nacimiento: "14/12/2001", edad: 24, nacionalidad: "Brasil" },
            { id: 16, nombre: "Davide Frattesi", posicion: "Mediocampista Central", nacimiento: "22/09/1999", edad: 26, nacionalidad: "Italia" },
            { id: 17, nombre: "Andy Diouf", posicion: "Mediocampista Central", nacimiento: "17/05/2003", edad: 23, nacionalidad: "Francia" },
            { id: 20, nombre: "Hakan Calhanoglu", posicion: "Centrocampista defensivo", nacimiento: "08/02/1994", edad: 32, nacionalidad: "Turquía" },
            { id: 22, nombre: "Henrik Mkhitaryan", posicion: "Mediocampista Central", nacimiento: "21/01/1989", edad: 37, nacionalidad: "Armenia" },
            { id: 23, nombre: "Nicolo Barella", posicion: "Mediocampista Central", nacimiento: "07/02/1997", edad: 29, nacionalidad: "Italia" },
            { id: 9, nombre: "Marcus Thuram", posicion: "Centro Delantero", nacimiento: "06/08/1997", edad: 28, nacionalidad: "Francia" },
            { id: 10, nombre: "Lautaro Martínez", posicion: "Centro Delantero", nacimiento: "22/08/1997", edad: 28, nacionalidad: "Argentina" },
            { id: 14, nombre: "Ange-Yoan Bonny", posicion: "Centro Delantero", nacimiento: "25/10/2003", edad: 22, nacionalidad: "Francia" },
            { id: 94, nombre: "Pio Esposito", posicion: "Centro Delantero", nacimiento: "28/06/2005", edad: 20, nacionalidad: "Italia" }
        ]
    },

    {
        id: 12,
        escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/960px-Logo_of_AC_Milan.svg.png",
        alt: "Escudo Milan",
        nombre: "AC Milan",
        fundacionClub: "28 de noviemre de 1899",
        descripcion: "La Associazione Calcio Milan, popularmente conocida como A. C. Milan y fundada el 28 de noviembre de 1899 bajo el nombre de Milan Foot-Ball & Cricket Club, es una histórica y laureada institución deportiva italiana con sede en la ciudad de Milán. Identificado por su tradicional indumentaria rojinegra que le otorga el apodo de equipo «rossonero», disputa sus encuentros como local en el imponente estadio San Siro (Giuseppe Meazza), el recinto más grande de Italia que comparte con su clásico rival, el Inter de Milán, con quien protagoniza el vibrante «Derby della Madonnina». A nivel nacional, es uno de los clubes más importantes de la Serie A —competición en la que ostenta el récord absoluto de 58 partidos consecutivos sin perder en las grandes ligas europeas— y acumula 19 «scudetti», cinco Copas de Italia y ocho Supercopas. Sin embargo, su mayor prestigio radica en el ámbito internacional, donde se consagra como el primer club italiano en ganar la Copa de Europa y el tercero en el continente con mayor cantidad de títulos oficiales (20), destacando en sus vitrinas siete Ligas de Campeones de la UEFA —solo por detrás del Real Madrid—, cuatro trofeos mundiales (tres Copas Intercontinentales y un Mundial de Clubes), cinco Supercopas de Europa y dos Recopas. Toda esta grandeza deportiva, sumada a los múltiples Balones de Oro obtenidos por sus históricas leyendas, lo ha consolidado como uno de los clubes más ricos, influyentes y reconocidos a nivel global.",
        liga: "Serie A",
        pais: "Italia",
        estadio: "https://i.pinimg.com/736x/5b/38/8a/5b388ae87332e066f427c4df70316ce9.jpg",
        altEstadio: "Imagen estadio",
        fundacion: 1926,
        nombreEstadio: "Estadio San Sario",
        capacidadEstadio: 80.018,
        ubicacion: "Milano, Italia",
        jugadores: [
            { id: null, nombre: "Ruben Amorim", posicion: "Entrenador", nacimiento: "27/01/1985", edad: 41, nacionalidad: "Portugal" },
            { id: null, nombre: "Marco Landucci", posicion: "Asistente tecnico", nacimiento: "25/03/1964", edad: 62, nacionalidad: "Italia" },
            { id: 1, nombre: "Pietro Terracciano", posicion: "Arquero", nacimiento: "08/03/1990", edad: 36, nacionalidad: "Italia" },
            { id: 16, nombre: "Mike Maignan", posicion: "Arquero", nacimiento: "03/07/1995", edad: 30, nacionalidad: "Francia" },
            { id: 96, nombre: "Lorenzo Torriani", posicion: "Arquero", nacimiento: "31/01/2005", edad: 21, nacionalidad: "Italia" },
            { id: 2, nombre: "Pervis Estupiñán", posicion: "Defensa Lateral Izquierdo", nacimiento: "21/01/1998", edad: 28, nacionalidad: "Ecuador" },
            { id: 5, nombre: "Koni De Winter", posicion: "Defensa Central", nacimiento: "12/06/2002", edad: 24, nacionalidad: "Bélgica" },
            { id: 23, nombre: "Fikayo Tomori", posicion: "Defensa Central", nacimiento: "19/12/1997", edad: 28, nacionalidad: "Inglaterra" },
            { id: 24, nombre: "Zachary Athekame", posicion: "Defensa Lateral Derecho", nacimiento: "13/12/2004", edad: 21, nacionalidad: "Suiza" },
            { id: 27, nombre: "David Odogu", posicion: "Defensa Central", nacimiento: "03/06/2006", edad: 20, nacionalidad: "Alemania" },
            { id: 31, nombre: "Strahinja Pavlovic", posicion: "Defensa Central", nacimiento: "24/05/2001", edad: 25, nacionalidad: "Serbia" },
            { id: 33, nombre: "Davide Bartesaghi", posicion: "Defensa Lateral Izquierdo", nacimiento: "29/12/2005", edad: 20, nacionalidad: "Italia" },
            { id: 46, nombre: "Matteo Gabbia", posicion: "Defensa Central", nacimiento: "21/10/1999", edad: 26, nacionalidad: "Italia" },
            { id: 4, nombre: "Samuele Ricci", posicion: "Centrocampista defensivo", nacimiento: "21/08/2001", edad: 24, nacionalidad: "Italia" },
            { id: 8, nombre: "Ruben Loftus-Cheek", posicion: "Mediocampista Central", nacimiento: "23/01/1996", edad: 30, nacionalidad: "Inglaterra" },
            { id: 12, nombre: "Adrien Rabiot", posicion: "Mediocampista Central", nacimiento: "03/04/1995", edad: 31, nacionalidad: "Francia" },
            { id: 14, nombre: "Luka Modric", posicion: "Mediocampista Central", nacimiento: "09/09/1985", edad: 40, nacionalidad: "Croacia" },
            { id: 19, nombre: "Youssouf Fofana", posicion: "Centrocampista defensivo", nacimiento: "10/01/1999", edad: 27, nacionalidad: "Francia" },
            { id: 30, nombre: "Ardon Jashari", posicion: "Centrocampista defensivo", nacimiento: "30/07/2002", edad: 23, nacionalidad: "Suiza" },
            { id: 56, nombre: "Alexis Saelemaekers", posicion: "Volante Derecho", nacimiento: "27/06/1999", edad: 26, nacionalidad: "Bélgica" },
            { id: 7, nombre: "Santiago Giménez", posicion: "Centro Delantero", nacimiento: "18/04/2001", edad: 25, nacionalidad: "México" },
            { id: 9, nombre: "Niclas Füllkrug", posicion: "Centro Delantero", nacimiento: "09/02/1993", edad: 33, nacionalidad: "Alemania" },
            { id: 10, nombre: "Rafael Leão", posicion: "Delantero Izquierdo", nacimiento: "10/06/1999", edad: 27, nacionalidad: "Portugal" },
            { id: 11, nombre: "Christian Pulisic", posicion: "Delantero Derecho", nacimiento: "18/09/1998", edad: 27, nacionalidad: "Estados Unidos" },
            { id: 18, nombre: "Christopher Nkunku", posicion: "Centro Delantero", nacimiento: "14/11/1997", edad: 28, nacionalidad: "Francia" }
        ]
    }

]